title: Wind
subtitle: null
description: null
author: Suex Cxine
language: null
timezone: null
url: 'http://yoursite.com'
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: null
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
theme: yilia
swiftype_key: JHUEjYw3wttpVnzcf9Ft
deploy:
  type: git
  repo:
      github: git@github.com:suexcxine/suexcxine.github.io.git,master
      coding: git@git.coding.net:suexcxine/suexcxine.git,gitcafe-pages
marked: {smartypants: false}
jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true
# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: false
  scriptFrom: local # 默认
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  model:
    scale: 1
    # hHeadPos: 0.5
    # vHeadPos: 0.618
    use: live2d-widget-model-miku # npm-module package name
  display:
    superSample: 2
    position: left
    width: 200
    height: 400
    hOffset: -10
    vOffset: -50
  mobile:
    show: true # 手机中是否展示
    scale: 0.5
  react:
    opacityDefault: 0.7
    opacityOnHover: 0.2

